mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("restaurant/", include("restaurant.urls")),
    path("admin/", admin.site.urls),
]

mysite/restaurant/urls.py
from django.urls import path

from . import views

app_name = "restaurant"
urlpatterns = [
    path("", views.index, name="index"),
    path("add_product", views.add_product, name="add_product"),
    path("product_list", views.product_list, name="product_list"),
    path("add_order", views.add_order, name="add_order"),
    path("customer_list", views.customer_list, name="customer_list"),
    path("order_list", views.order_list, name="order_list"),
    path("show_order/<int:id>", views.show_order, name="show_order"),
]

mysite/restaurant/models.py
from django.db import models


# Create your models here.
class Customer(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30, null=True)
    address = models.CharField(default="", max_length=500, null=True)
    is_male = models.BooleanField(default=True, null=True)
    
    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Product(models.Model):
    CATEGORIES = [
        ("beverage", "beverage"),
        ("meal", "meal"),
        ("appetizer", "appetizer"),
    ]
    category = models.CharField(max_length=10, choices=CATEGORIES, default="beverage")
    name = models.CharField(max_length=30, unique=True)
    price = models.DecimalField(max_digits=10, decimal_places=0)

    def __str__(self):
        return self.name


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, through="ProductsInOrder")
    date = models.DateTimeField()

class ProductsInOrder(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    number = models.IntegerField()

class Purchase(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    date = models.DateTimeField()
    number = models.IntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=0)

mysite/restaurant/forms.py
from django import forms


class ProductForm(forms.Form):
    name = forms.CharField(max_length=30, widget=forms.TextInput(attrs={"placeholder": "چلو گوشت",}))
    price = forms.DecimalField(
        max_digits=10, decimal_places=0, widget=forms.NumberInput(attrs={"placeholder": "100000"})
    )

mysite/restaurant/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.utils import timezone

import jdatetime
import datetime

import re

from .models import *


# Create your views here.
def index(request):
    return render(request, "restaurant/index.html")


def add_product(request):
    error_message = ""
    if request.method == "POST":
        try:
            category = request.POST["category"]
            name = request.POST["name"]
            price = request.POST["price"]
            try:
                product = Product.objects.get(name=name)
            except:
                product = None
            if product:
                raise KeyError("duplicate product")
            new_product = Product(category=category, name=name, price=price)
            new_product.save()
            return redirect(reverse("restaurant:product_list"))
        except KeyError:
            error_message = "محصول تکراری است."
        except:
            error_message = "لطفا مقادیر را درست وارد کنید."

    return render(
        request, "restaurant/addproduct.html", context={"error_message": error_message}
    )


def product_list(request):
    error_message = ""
    if request.method == "POST":
        try:
            id = request.POST["id"]
            category = request.POST["category"]
            name = request.POST["name"]
            price = request.POST["price"]
            if id == "":
                product = Product(category=category, name=name, price=price)
                product.save()
            else:
                product = get_object_or_404(Product, id=id)
                if "delete" in request.POST:
                    product.delete()
                else:
                    product.category = category
                    product.name = name
                    product.price = price
                    product.save()
            return redirect(reverse("restaurant:product_list"))
        except Exception:
            error_message = "لطفا مقادیر را درست وارد کنید."

    appetizers = Product.objects.all().filter(category="appetizer")
    beverages = Product.objects.all().filter(category="beverage")
    meals = Product.objects.all().filter(category="meal")
    context = {
        "appetizers": appetizers,
        "beverages": beverages,
        "meals": meals,
        "error_message": error_message,
    }
    return render(request, "restaurant/productlist.html", context)


def add_order(request):
    error_message = ""
    if request.method == "POST":
        try:
            number_of_products = 0
            pat1 = re.compile("^product(\d*)-id$")
            for key in request.POST:
                if request.POST[key] == "":
                    raise Exception("nothing should be empty.")
                if pat1.match(key):
                    number_of_products += 1
            customer_id = request.POST["customer_id"]
            customer = Customer.objects.get(id=customer_id)
            cur_datetime = datetime.datetime.now()
            order = Order(customer=customer, date=cur_datetime)
            order.save()
            for i in range(number_of_products):
                id = request.POST[f"product{i}-id"]
                product = Product.objects.get(id=id)
                number = request.POST[f"product{i}-number"]
                ProductsInOrder.objects.create(
                    order=order, product=product, number=number
                )
            return redirect(reverse("restaurant:add_order"))
        except Exception as e:
            error_message = "لطفا مقادیر را درست وارد کنید."

    persons = Customer.objects.all()
    appetizers = Product.objects.all().filter(category="appetizer")
    beverages = Product.objects.all().filter(category="beverage")
    meals = Product.objects.all().filter(category="meal")
    context = {
        "appetizers": appetizers,
        "beverages": beverages,
        "meals": meals,
        "persons": persons,
        "error_message": error_message,
    }
    return render(request, "restaurant/addorder.html", context)


def customer_list(request):
    error_message = ""
    if request.method == "POST":
        try:
            customer_id = request.POST["customer_id"]
            first_name = request.POST["first_name"]
            last_name = request.POST["last_name"]
            gender = request.POST["gender"]
            is_male = None
            if gender == "male":
                is_male = True
            elif gender == "female":
                is_male = False
            address = request.POST["address"]
            delete = None
            if "delete" in request.POST:
                delete = request.POST["delete"]
            if customer_id == "":
                customer = Customer(
                    first_name=first_name,
                    last_name=last_name,
                    is_male=is_male,
                    address=address,
                )
                customer.save()
            else:
                customer = Customer.objects.get(id=customer_id)
                if delete:
                    customer.delete()
                else:
                    customer.first_name = first_name
                    customer.last_name = last_name
                    customer.is_male = is_male
                    customer.address = address
                    customer.save()
            return redirect(reverse("restaurant:customer_list"))
        except Exception as e:
            error_message = "مقادیر را درست وارد کنید."

    customers = Customer.objects.all()
    context = {"customers": customers, "error_message": error_message}
    return render(request, "restaurant/customerlist.html", context)


def order_list(request):
    from_date = datetime.datetime.min + datetime.timedelta(1)
    to_date = datetime.datetime.now()
    if request.method == "POST":
        try:
            jfrom_date = jdatetime.datetime.strptime(
                request.POST["from_date"], r"%Y/%m/%d %H:%M:%S"
            )
            jto_date = jdatetime.datetime.strptime(
                request.POST["to_date"], r"%Y/%m/%d %H:%M:%S"
            )
            from_date = jfrom_date.togregorian()
            to_date = jto_date.togregorian()
        except:
            pass
    orders = (
        Order.objects.filter(date__lte=to_date)
        .filter(date__gte=from_date)
        .order_by("-date")
    )

    output_orders = []
    total_sum = 0
    for order in orders:
        products_in_order = ProductsInOrder.objects.filter(order=order)
        order_sum = 0
        for product_in_order in products_in_order:
            order_sum += product_in_order.product.price * product_in_order.number
        total_sum += order_sum
        persian_date = jdatetime.datetime.fromgregorian(datetime=order.date).strftime(
            r"%Y-%m-%d %H:%M:%S"
        )
        output_orders.append(
            [
                order.id,
                f"{order.customer.first_name} {order.customer.last_name}",
                persian_date,
                order_sum,
            ]
        )
    context = {"output_orders": output_orders, "total_sum": total_sum}
    return render(request, "restaurant/orderlist.html", context)


def show_order(request, id):
    error_message = ""
    order = Order.objects.get(id=id)
    if request.method == "POST":
        if "delete_order" in request.POST:
            order.delete()
            return redirect(reverse("restaurant:order_list"))
        try:
            number_of_products = 0
            pat1 = re.compile("^product(\d*)-id$")
            for key in request.POST:
                if request.POST[key] == "":
                    raise Exception("nothing should be empty.")
                if pat1.match(key):
                    number_of_products += 1
            customer_id = request.POST["customer_id"]
            customer = Customer.objects.get(id=customer_id)

            order.customer = customer
            order_datetime = jdatetime.datetime.strptime(
                request.POST["date"], r"%Y/%m/%d %H:%M:%S"
            ).togregorian()
            for product_in_order in ProductsInOrder.objects.filter(order=order):
                product_in_order.delete()
            order.date = order_datetime
            order.save()
            for i in range(number_of_products):
                product_id = request.POST[f"product{i}-id"]
                product = Product.objects.get(id=product_id)
                number = request.POST[f"product{i}-number"]
                ProductsInOrder.objects.create(
                    order=order, product=product, number=number
                )
            return redirect(reverse("restaurant:show_order", kwargs={"id": id}))
        except Exception as e:
            error_message = "لطفا مقادیر را درست وارد کنید."
    products_in_order = ProductsInOrder.objects.filter(order=order)
    ouptput_products = []
    for product_in_order in products_in_order:
        product = product_in_order.product
        number = product_in_order.number
        ouptput_products.append((product, number, product.price * number))

    customer = order.customer
    persons = Customer.objects.all()
    appetizers = Product.objects.all().filter(category="appetizer")
    beverages = Product.objects.all().filter(category="beverage")
    meals = Product.objects.all().filter(category="meal")
    context = {
        "appetizers": appetizers,
        "beverages": beverages,
        "meals": meals,
        "persons": persons,
        "error_message": error_message,
        "order": order,
        "customer": customer,
        "customer_full_name": customer.first_name + " " + customer.last_name,
        "order_persian_date": jdatetime.datetime.fromgregorian(
            datetime=order.date
        ).strftime(f"%Y/%m/%d %H:%M:%S"),
        "output_products": ouptput_products,
    }

mysite/restaurant/templates/restaurant/addorder.html
{% extends "restaurant/base.html" %}

{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'restaurant/addorder.css' %}" />
<script defer src="{% static 'restaurant/addorder.js' %}"></script>
{% endblock %}

{% block title %}
افزودن سفارش
{% endblock %}

{% block content %}
{% if error_message %}
<p class="error-message"> {{ error_message }}</p>
{% endif %}
<form action="" method="POST">
    {% csrf_token %}
    <div id="person">
        <button type="button" class="btn" id="select-person-button" onclick="togglePersonsPopup()">انتخاب
            گیرنده</button>
        <input id="person-id" name="customer_id" class="hidden">
        <input id="person-name" readonly value="">
        <input id="person-address" readonly value="">
    </div>
    <div class="product-table-wrapper">
        <table id="product-table" class="product-table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>نام</th>
                    <th> قیمت (تومان)</th>
                    <th>تعداد</th>
                    <th>فی (تومان)</th>
                </tr>
            </thead>
            <tbody id="product-table-body">
            </tbody>
            <tfoot>
                <tr>
                    <th colspan="4">
                        جمع
                    </th>
                    <td id="sum-cell"></td>
                </tr>
            </tfoot>
        </table>
    </div>
    <div class="add-row-wrapper">
        <button type="button" class="btn" id="add-row" onclick="addRow()">افزودن سطر</button>
        <button type="button" class="btn red-btn" id="delete-row" onclick="deleteRow()">حذف سطر آخر</button>
    </div>

    <div class="button-wrapper">
        <button type="submit" class="btn submit-btn">تایید سفارش</button>
        <button type="button" class="btn" onclick="printTable()">چاپ فیش</button>
    </div>
</form>


<div id="persons-popup" class="hidden">
    <div id="persons-popup-window">
        <header>
            <div></div>
            <h3>مشتری‌ها</h3>
            <div id="close-person-popup" onclick="togglePersonsPopup()">✕</div>
        </header>
        <main>
            <table id="persons-table">
                <thead>
                    <tr>
                        <th>نام</th>
                        <th>نام خانوادگی</th>
                        <th>آقا/خانم</th>
                        <th>آدرس</th>
                    </tr>
                </thead>
                <tbody>
                    {% for person in persons %}
                    <tr id="person-{{person.id}}" onclick="selectPerson(this.id)">
                        <td>{{person.first_name}}</td>
                        <td>{{person.last_name}}</td>
                        <td>
                            {% if person.is_male is True %}
                            آقا
                            {% elif person.is_male is False %}
                            خانم
                            {% endif%}
                        </td>
                        <td>{{person.address}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <div class="add-person-page-wrapper">
                <a id="add-person-page" class="btn" href="{% url 'restaurant:customer_list' %}">افزودن مشتری</a>
            </div>
        </main>
    </div>
</div>

<div id="products-popup" class="hidden">
    <div id="products-popup-window">
        <header>
            <div></div>
            <h3>محصولات</h3>
            <div id="close-person-popup" onclick="toggleProductsPopup()">✕</div>
        </header>
        <main>
            <div class="menu">
                <div class="category">
                    <h1 class="category-h">غذاها</h1>
                    <ul calss="category-list">
                        {% for meal in meals %}
                        <li>
                            <div class="box" id="meal-{{meal.id}}" onclick="selectProduct(this.id)">
                                <img src="" alt="">
                                <h1>{{meal.name}}</h1>
                                <p class="price">{{meal.price}}T</p>
                            </div>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="category">
                    <h1 class="category-h">نوشیدنی‌ها</h1>
                    <ul calss="category-list">
                        {% for beverage in beverages %}
                        <li>
                            <div class="box" id="beverage-{{beverage.id}}" onclick="selectProduct(this.id)">
                                <img src="" alt="">
                                <h1>{{beverage.name}}</h1>
                                <p class="price">{{beverage.price}}T</p>
                            </div>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="category">
                    <h1 class="category-h">مخلفات</h1>
                    <ul calss="category-list">
                        {% for appetizer in appetizers %}
                        <li>
                            <div class="box" id="appetizer-{{appetizer.id}}" onclick="selectProduct(this.id)">
                                <img src="" alt="">
                                <h1>{{appetizer.name}}</h1>
                                <p class="price">{{appetizer.price}}T</p>
                            </div>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </main>
    </div>
</div>
{% endblock %}

mysite/restaurant/templates/restaurant/addproduct.html
{% extends "restaurant/base.html" %}

{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'restaurant/addproduct.css' %}">
{% endblock %}

{% block title %}
افزودن محصول
{% endblock title %}

{% block content %}
<div class="wrapper">

    <h1 class="header">افزودن محصول</h1>
    <form action="" method="POST" class="addproduct-form">
        {% csrf_token %}
        {% if error_message %}
        <p class="error-message"> {{ error_message }}</p>
        {% endif %}
        <ul class="addproduct-form-list">
            <li>
                <label for="id_type">نوع محصول:</label>
                <select name="category" id="id_type">
                    <option value="meal">غذا</option>
                    <option value="beverage">نوشیدنی</option>
                    <option value="appetizer">مخلفات</option>
                </select>
            </li>
            <li>
                <label for="id_name">نام محصول: </label>
                <input type="text" name="name" placeholder="چلو گوشت" id="id_name">
            </li>
            <li>
                <label for="id_price">قیمت محصول (تومان): </label>
                <input type="number" name="price" placeholder="200000" required id="id_price">
            </li>
        </ul>
        <div class="addproduct-form-button">
            <button type="submit">تایید</button>
        </div>
    </form>
</div>
{% endblock content %}

mysite/restaurant/templates/restaurant/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="rtl">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'restaurant/base.css' %}">
    {% block head %}
    {% endblock head %}
    <title>
        {% block title %}
        my amazing site
        {% endblock title %}
    </title>
</head>

<body>
    <header>
        <nav class="navbar">

            <!-- NAVIGATION MENU -->
            <ul class="nav-links">

                <!-- USING HAMBURGER TOGGLE -->
                <input type="checkbox" id="checkbox_toggle" class="hamburger-checkbox" />
                <label for="checkbox_toggle" class="hamburger">&#9776;</label>

                <!-- NAVIGATION MENUS -->
                <div class="navmenu">
                    <li><a href="{% url 'restaurant:index' %}">خانه</a></li>
                    <li class="dropdown">
                        <p>سفارش‌ها</p>
                        <ul class="dropdown-content">
                            <li><a href="{% url 'restaurant:add_order' %}">افزودن سفارش</a></li>
                            <li><a href="{% url 'restaurant:order_list' %}">لیست سفارش‌ها</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <p>خریدها</p>
                        <ul class="dropdown-content">
                            <li><a href="">افزودن خرید</a></li>
                            <li><a href="">لیست خریدها</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <p>محصول‌ها</p>
                        <ul class="dropdown-content">
                            <li><a href="{% url 'restaurant:add_product'%}">افزودن محصول</a></li>
                            <li><a href="{% url 'restaurant:product_list' %}">لیست محصول‌ها</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="{% url 'restaurant:customer_list' %}">مشتری‌ها</a>
                    </li>
                </div>
            </ul>
        </nav>

    </header>
    <main>
        {% block content %}
        Content
        {% endblock content %}
    </main>
    <footer>
        درباره ی ما
    </footer>

</body>

</html>

mysite/restaurant/templates/restaurant/customerlist.html
{% extends "restaurant/base.html" %}

{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'restaurant/customerlist.css' %}">
<script defer src="{% static 'restaurant/customerlist.js' %}"></script>
{% endblock %}

{% block title %}
لیست سفارش‌ها
{% endblock %}

{% block content %}
{% if error_message %}
<p class="error-message">{{error_message}}</p>
{% endif %}
<table id="customers-table">
    <thead>
        <tr>
            <th>#</th>
            <th>نام</th>
            <th>نام خانوادگی</th>
            <th>آقا/خانم</th>
            <th>آدرس</th>
        </tr>
    </thead>
    <tbody>
        {% for customer in customers %}
        <tr onclick="clickOnCustomerTr(this.id)" id="customer-{{customer.id}}">
            <th>{{forloop.counter}}</th>
            <td>{{customer.first_name}}</td>
            <td>{{customer.last_name}}</td>
            <td>
                {% if customer.is_male is True %}
                آقا
                {% elif customer.is_male is False %}
                خانم
                {% endif %}
            </td>
            <td>
                {{customer.address}}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<div id="add-customer-wrapper">
    <button id="add-customer" class="btn" onclick="clickOnAddCustomer()">افزودن مشتری</button>
</div>

<div class="popup hidden">
    <div class="popup-window">
        <header>
            <h3> افزودن یا ویرایش مشتری </h3>
            <div class="close-popup" onclick="togglePopup()">✕</div>
        </header>
        <main>
            <form class="popup-from" action="" method="POST">
                {% csrf_token %}
                <input type="text" name="customer_id" id="customer-id" class="hidden">
                <ul class="addcustomer-form-list">
                    <li>
                        <label for="first-name">نام:</label>
                        <input type="text" id="first-name" name="first_name" placeholder="احمد" />
                    </li>
                    <li>
                        <label for="last-name">نام خانوادگی: </label>
                        <input type="text" name="last_name" id="last-name" placeholder="باغستانی">
                    </li>
                    <li>
                        <label for="address">آدرس:</label>
                        <input type="text" name="address" id="address" placeholder="خیابان آفرینش">
                    </li>
                    <li>
                        <label for="gender">جنسیت:</label>
                        <select id="gender" name="gender">
                            <option value="unknown">نامعلوم</option>
                            <option value="male">آقا</option>
                            <option value="female">خانم</option>
                        </select>
                    </li>
                    <li>

                        <label for="delete">
                            حذف کردن <input type="checkbox" name="delete" id="delete">
                        </label>
                    </li>
                </ul>
                <div class="addcustomer-form-button">
                    <button type="submit" class="btn">تایید</button>
                </div>
            </form>
        </main>
    </div>
</div>
{% endblock %}

mysite/restaurant/templates/restaurant/index.html
{% extends "restaurant/base.html" %}

{% block title %}
خانه
{% endblock title %}

{% block content %}
<h1>خانه</h1>
<p>لطفا از منو ی بالا گزینه ی مورد نظر را انتخاب کنید</p>
{% endblock content %}

mysite/restaurant/templates/restaurant/orderlist.html
{% extends "restaurant/base.html" %}

{% load static %}

{% block head %}
<link type="text/css" rel="stylesheet" href="{% static 'restaurant/jalalidatepicker.min.css' %}" />
<link rel="stylesheet" href="{% static 'restaurant/orderlist.css' %}">
<script src="{% static 'restaurant/jalalidatepicker.min.js' %}"></script>
<script defer src="{% static 'restaurant/orderlist.js' %}"></script>
{% endblock %}

{% block title %}
لیست سفارش‌ها
{% endblock %}

{% block content %}
<div class="form-wrapper">
    <form method="POST">
        {% csrf_token %}
        <div class="input-wrapper">
            <label for="from-date">
                از تاریخ:
                <input type="text" id="from-date" name="from_date" data-jdp>
                <span id="from-date-span"></span>
            </label>
            <label for="to-date">
                تا تاریخ:
                <input type="text" id="to-date" name="to_date" data-jdp>
                <span id="to-date-span"></span>

            </label>
            <button type="submit" class="btn">تایید</button>
        </div>
    </form>
</div>
<table id="orders-table">
    <thead>
        <tr>
            <th>#</th>
            <th>نام و نام‌خانوادگی مشتری</th>
            <th>تاریخ و ساعت</th>
            <th>میزان دریافتی (تومان)</th>
        </tr>
    </thead>
    <tbody>
        {% for order_id,customer_name,persian_date,order_sum in output_orders %}
            <tr onclick="goToURL(`{% url 'restaurant:show_order' order_id%}`)">
                <th>{{forloop.counter}}</th>
                <td>{{customer_name}}</td>
                <td>{{persian_date}}</td>
                <td>{{order_sum}}</td>
            </tr>
        {% endfor %}
    </tbody>
    <tfoot>
        <tr>
            <th colspan="3">جمع</th>
            <td>{{total_sum}}</td>
        </tr>
        
    </tfoot>
</table>
{% endblock %}

mysite/restaurant/templates/restaurant/productlist.html
{% extends "restaurant/base.html" %}

{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'restaurant/productlist.css' %}">
<script defer src="{% static 'restaurant/productlist.js' %}"></script>
{% endblock %}

{% block title %}
لیست محصولات
{% endblock %}

{% block content %}
<h1 class="" style="text-align: center;">لیست محصولات</h1>
{% if error_message %}
<p class="error-message"> {{ error_message }}</p>
{% endif %}
<div class="menu">
    <div class="category">
        <h1 class="category-h">غذاها</h1>
        <ul calss="category-list">
            {% for meal in meals %}
            <li>
                <div class="box" id="meal-{{meal.id}}" onclick="showEditPopup(this.id)">
                    <img src="" alt="">
                    <h1>{{meal.name}}</h1>
                    <p class="price">{{meal.price}}T</p>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
    <div class="category">
        <h1 class="category-h">نوشیدنی‌ها</h1>
        <ul calss="category-list">
            {% for beverage in beverages %}
            <li>
                <div class="box" id="beverage-{{beverage.id}}" onclick="showEditPopup(this.id)">
                    <img src="" alt="">
                    <h1>{{beverage.name}}</h1>
                    <p class="price">{{beverage.price}}T</p>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
    <div class="category">
        <h1 class="category-h">مخلفات</h1>
        <ul calss="category-list">
            {% for appetizer in appetizers %}
            <li>
                <div class="box" id="appetizer-{{appetizer.id}}" onclick="showEditPopup(this.id)">
                    <img src="" alt="">
                    <h1>{{appetizer.name}}</h1>
                    <p class="price">{{appetizer.price}}T</p>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
<div class="addproduct-button-wrapper">
    <button id="addproduct-button"class="btn" onclick="showNewPopup()">افزودن محصول</button>
</div>
<div class="popup hidden">
    <div class="popup-window">
        <header>
            <h3> افزودن یا ویرایش محصول </h3>
            <div class="close-popup">✕</div>
        </header>
        <main>
            <form class="popup-from" action="" method="POST">
                {% csrf_token %}
                <input type="text" name="id" id="id_id" class="hidden">
                <ul class="addproduct-form-list">
                    <li>
                        <label for="id_type">نوع محصول:</label>
                        <select name="category" id="id_type">
                            <option value="meal">غذا</option>
                            <option value="beverage">نوشیدنی</option>
                            <option value="appetizer">مخلفات</option>
                        </select>
                    </li>
                    <li>
                        <label for="id_name">نام محصول: </label>
                        <input type="text" name="name" placeholder="چلو گوشت" id="id_name">
                    </li>
                    <li>
                        <label for="id_price">قیمت محصول (تومان): </label>
                        <input type="number" name="price" placeholder="200000" required id="id_price">
                    </li>
                    <label for="id_delete">
                        حذف کردن
                        <input type="checkbox" name="delete" id="id_delete">
                    </label>
                </ul>
                <div class="addproduct-form-button">
                    <button type="submit" class="btn">تایید</button>
                </div>
            </form>
        </main>
    </div>
</div>
{% endblock %}